[tool.isort]
line_length=88
multi_line_output=3
include_trailing_comma=true
use_parentheses=true
known_third_party=["attr", "bs4", "cleverwrap", "feedparser", "forecastiopy", "freezegun", "geoip2", "googlemaps", "imgurpython", "irclib", "isodate", "lxml", "mcstatus", "multidict", "nltk", "pytest", "requests", "responses", "sqlalchemy", "tweepy", "venusian", "watchdog", "yarl"]

[tool.black]
line-length = 88
target-version = ['py35']
include = '\.pyi?$'
exclude = '''
(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
    | venv
  )/
)
'''
